image: python:3.11-slim  # Use Python 3.11

stages:
  - alerts

sso-alerts:
  stage: alerts
  before_script:
    - pip install --upgrade pip
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install numpy==1.23.5 pandas==1.5.3 yfinance==0.2.28  # Install fixed versions
    - python sso_telegram_alerts.py  # Run your script
  only:
    - schedules  # Run only on scheduled triggers
